### PR TITLE
First route!

### PR DESCRIPTION
**Pull request by projectweekend**

### CODE REVIEW

**Comment by Tathanen** [comment]
Ha, this fuckin' thing as the sample article, wonderful.

**Comment by Tathanen** [comment]
Using nsider as one word is fine in slugs and vars n shit, but the proper name should be N-Sider with hyphen and capital S in doc.  Otherwise LGTM for now, may or may not request changes when I begin actual integration.

**Comment by projectweekend** [comment]
Got it. So `N-Sider` in the README and stuff

**Comment by Tathanen** [comment]
:+1:

**Pull request merged**
